// <auto-generated />
namespace SGAP_Sistema_de_Gerenciamento_de_Alunos_e_Professores.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Enderecomaxlengt500 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Enderecomaxlengt500));
        
        string IMigrationMetadata.Id
        {
            get { return "202007102224349_Enderecomaxlengt500"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
